---
title: "IAU2 - Trabajo Práctico Final"
author: "Alumnos: Guadalupe Atienza, Georgina Gorlero, Felipe Mesel"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(vroom)
library(janitor)
library(lubridate)
library(ggmap)
library(sf)
library(leaflet)
library(patchwork)
```

```{r}
properati_CABA_alq <- vroom("data/properati_CABA_alq")
properati_CABA_venta <- vroom("data/properati_CABA_venta")
```

```{r}
properati_CABA_alq <- properati_CABA_alq %>%
                      mutate(price=if_else(currency == "ARS", 
                                           round(price/(104.72*1.65),2), price),     
                             currency= "USD") %>%
                      filter(price>50 & price < 10000 & surface_total>18 &  surface_total < 750)
```

```{r}
properati_CABA_venta <-  properati_CABA_venta %>%
                         mutate(price=if_else(currency == "ARS",
                                              round(price/(104.72*1.65),2), price), 
                                currency= "USD") %>%
                         filter(price>30000 & price < 10000000 & surface_total>18 &  surface_total < 750)
```

```{r}
barrios_CABA <- read_sf("data/barrios.geojson")
comunas_CABA <- read_sf("data/CABA_comunas.geojson")

barrios_CABA$COMUNA <- as.factor(round(as.numeric(barrios_CABA$COMUNA)))
comunas_CABA$COMUNAS <- as.factor(round(as.numeric(comunas_CABA$COMUNAS)))
```


```{r}
properati_2021 <- merge.data.frame(properati_CABA_venta, properati_CABA_alq, all=T) %>% 
                  st_as_sf(coords=c("lon","lat"), crs=4326)

properati_2021 <- properati_2021 %>% 
                  st_join(barrios_CABA) %>% 
                  filter(!is.na(BARRIO)) %>% 
                  mutate(surface_total=if_else(is.na(surface_total),
                                               surface_covered,surface_total))%>% 
                  filter(!is.na(surface_total))%>% 
                  mutate(precio_m2=round((price/surface_total),2))%>% 
                  select(tipo_propiedad = property_type,
                  tipo_operacion=operation_type,
                  sup_cubierta=surface_covered,
                  sup_total=surface_total,
                  precio=price,
                  precio_m2,
                  barrio=BARRIO,
                  comuna=COMUNA,
                  geometria=geometry)
```

```{r}
properati_2021$comuna <- as.factor(round(as.numeric(properati_2021$comuna)))
```

```{r}
grafico_1  <- properati_2021%>% 
filter(tipo_operacion== "Venta") %>%
  ggplot() + 
  geom_point(aes(x = sup_total, y = precio/1000, color = tipo_propiedad, alpha=0.8)) +
  theme_minimal() +
  scale_color_brewer (palette = 1) +
  theme(plot.title = element_text(face="bold", size=13)) +
  theme(axis.title.x = element_text(face="bold", vjust=-0.5, colour="firebrick", size=12)) +
  theme(axis.title.y = element_text(face="bold", vjust=-0.5, colour="firebrick", size=12)) + 
  labs(title = "Gráfico 1. Superficie y precio en la oferta de inmuebles en venta en CABA", 
       subtitle = "Precio de los inmuebles en venta según superficie y tipo de propiedad en CABA",
       x = "Superficie cubierta (m2)",
       y = "Precio (miles de USD)",
       caption = "fuente: Properati - año 2021",
       color ="tipo de propiedad") + 
  scale_y_continuous(breaks = seq(0, 10000, 1000)) +
  scale_x_continuous(breaks = seq(0, 750, 50)) +
  guides(alpha = FALSE) +
  geom_smooth(aes(x=sup_total, y=precio/1000), method = "lm", colour="dodgerblue4")
```

```{r}
grafico_2 <- properati_2021%>% 
filter(tipo_operacion== "Alquiler") %>%
  ggplot() + 
  geom_point(aes(x = sup_total, y = precio, color = tipo_propiedad, alpha=0.8)) +
  theme_minimal() +
  scale_color_brewer (palette = 1) +
  theme(plot.title = element_text(face="bold", size=13)) +
  theme(axis.title.x = element_text(face="bold", vjust=-0.5, colour="firebrick", size=12)) +
  theme(axis.title.y = element_text(face="bold", vjust=-0.5, colour="firebrick", size=12)) + 
  labs(title = "Gráfico 2.Superficie y precio en la oferta de inmuebles en alquiler en CABA", 
       subtitle = "Precio de los inmuebles en alquiler según superficie y tipo de propiedad en CABA",
       x = "Superficie cubierta (m2)",
       y = "Precio (en USD)",
       caption = "fuente: Properati - año 2021",
       color ="tipo de propiedad") + 
  scale_y_continuous(breaks = seq(0, 10000, 1000)) +
  scale_x_continuous(breaks = seq(0, 750, 50)) +
  guides(alpha = FALSE) +
  geom_smooth(aes(x=sup_total, y=precio), method = "lm", colour="dodgerblue4")
```

```{r}
properati_2021_pm_comuna <- properati_2021 %>%
                            st_set_geometry(NULL) %>% 
                            group_by(comuna,  tipo_propiedad, tipo_operacion) %>%
                            summarise(precio_m2=round(mean(precio_m2),2),
                                      precio=round(mean(precio)))

properati_2021_pm_comuna_resumen <- properati_2021 %>%
                                    st_set_geometry(NULL) %>% 
                                    group_by(comuna, tipo_operacion) %>%
                                    summarise(precio_m2=round(mean(precio_m2),2),
                                    precio=round(mean(precio)))
```

```{r, fig.width=13, fig.height=5}
grafico_3 <- ggplot() +
  geom_label(data=properati_2021_pm_comuna_resumen%>%
             filter(tipo_operacion=="Venta"), 
             mapping= aes(x=fct_reorder(comuna,desc(precio_m2)), y=precio_m2+500,
             label=round(precio_m2)))+
  geom_bar(data=properati_2021_pm_comuna%>%
                filter(tipo_operacion=="Venta"), 
           mapping= aes(x=comuna, y=precio_m2, fill=tipo_propiedad), position="dodge", stat="identity") +
    theme_minimal() +
    theme(plot.title = element_text(face="bold", size=15)) +
    theme(axis.title.x = element_text(face="bold", vjust=-0.5, colour="firebrick", size=12)) +
    theme(axis.title.y = element_text(face="bold", vjust=-0.5, colour="firebrick", size=12)) + 
    scale_fill_manual(values = c("gray85", "lightskyblue", "dodgerblue1")) +
    labs(title = "Gráfico 3. Ranking de precios de venta", 
         subtitle = "Precio promedio por metro cuadrado por comuna y tipo de propiedad en la Ciudad de Buenos Aires",
         x = "Comuna",
         y = "Precio promedio (USD) por m2",
         caption = "fuente: Properati - año 2021. En las etiquetas se muestra el precio promedio del m2 para la comuna.",
         fill = "Tipo de Propiedad")
```


```{r, fig.width=13, fig.height=5}
grafico_4 <- ggplot() +
  geom_label(data=properati_2021_pm_comuna_resumen%>%
             filter(tipo_operacion=="Alquiler"), 
             mapping= aes(x=fct_reorder(comuna,desc(precio_m2)), y=precio_m2+2,
             label=precio_m2))+
  geom_bar(data=properati_2021_pm_comuna%>%
           filter(tipo_operacion=="Alquiler"), 
           mapping= aes(x=comuna, y=precio_m2, fill=tipo_propiedad), position="dodge", stat="identity") +
    theme_minimal() +
    theme(plot.title = element_text(face="bold", size=15)) +
    theme(axis.title.x = element_text(face="bold", vjust=-0.5, colour="firebrick", size=12)) +
    theme(axis.title.y = element_text(face="bold", vjust=-0.5, colour="firebrick", size=12)) + 
    scale_fill_manual(values = c("gray85", "lightskyblue", "dodgerblue1")) +
    labs(title = "Gráfico 4. Ranking de precios de alquiler", 
         subtitle = "Precio promedio por metro cuadrado por comuna y tipo de propiedad en la Ciudad de Buenos Aires",
         x = "Comuna",
         y = "Precio promedio (USD) por m2",
         caption = "fuente: Properati - año 2021. En las etiquetas se muestra el precio promedio del m2 para la comuna.",
         fill = "Tipo de Propiedad")
```

```{r, fig.width=10, fig.height=10}
(grafico_1 / grafico_3)
```

```{r, fig.width=10, fig.height=10}
(grafico_2 / grafico_4)
```
```{r}
precios_por_barrio <- properati_2021 %>% 
                      filter(tipo_operacion=="Venta") %>% 
                      st_set_geometry(NULL) %>% 
                      group_by(barrio) %>%
                      summarise(precio_m2=round(mean(precio_m2),2),
                      precio=round(mean(precio)))


precios_por_barrio <- left_join(barrios_CABA, precios_por_barrio, 
                                by=c("BARRIO"="barrio"))
```

```{r}
ggplot()+
  geom_sf(data=precios_por_barrio, mapping=aes(fill=precio_m2), color=NA) +
  geom_sf(data=comunas_CABA, color="white", fill=NA) +
    labs(title = "Mapa 1. El mapa de los precios de la Ciudad",
         subtitle = "Precio promedio del m2 por barrio",
         fill = "Precio promedio (U$D/m2)",
         caption= "Fuente: Properati 2021") +
  scale_fill_distiller(palette = "Spectral") +
  theme_void() + 
  theme(plot.title = element_text(face="bold", size=15))
```
```{r}
precios_por_comuna_resumen <- comunas_CABA %>% 
                              left_join(properati_2021_pm_comuna_resumen,
                              by=c("COMUNAS"="comuna")) %>% 
                              filter(tipo_operacion=="Venta")

precios_por_comuna <- comunas_CABA %>% 
                      left_join(properati_2021_pm_comuna,
                                by=c("COMUNAS"="comuna")) %>% 
                      filter(tipo_operacion=="Venta")
```


```{r}
ggplot(data=precios_por_comuna_resumen)+
  geom_sf(mapping=aes(fill=precio_m2), color="white") +
  geom_sf_label(mapping=aes(label=precio), fill="grey90", color="grey30", size=2) +
    labs(title = "Mapa 2. El mapa de los precios de la Ciudad",
         subtitle = "Precio promedio y precio promedio del m2 por comuna",
         fill = "Precio promedio (U$D/m2)",
         caption= "Fuente: Properati 2021") +
  scale_fill_distiller(palette = "Spectral") +
  theme_void() + 
  theme(plot.title = element_text(face="bold", size=15))
```


```{r, fig.width=15, fig.height=7}
ggplot()+
  geom_sf(data=precios_por_comuna, mapping=aes(fill=precio_m2), color="white") +
    labs(title = "Mapa 3. El mapa de los precios de la Ciudad",
         subtitle = "Precio promedio del m2 por comuna segun tipo de propiedad",
         fill = "Precio promedio (U$D/m2)",
         caption= "Fuente: Properati 2021") +
  scale_fill_distiller(palette = "Spectral") +
  theme_void() + 
  theme(plot.title = element_text(face="bold", size=15))+
  facet_wrap(~tipo_propiedad)
```

```{r}

```

